### DISCUSSION TITLE
How to remove the horizontal line

### DISCUSSION THREAD

**Discussion by robyhuzwandar** [stipsan/react-spring-bottom-sheet#241] [Q&A]
I don't want to show this line, how to remove ?

<img width="693" alt="Screen Shot 2022-11-14 at 13 28 50" src="https://user-images.githubusercontent.com/20414047/201582514-50dd5c04-29c0-4bb9-9a1e-8a52230faf38.png">

**Comment by la55u** [comment]
In your CSS file:
```css
:root {
  --rsbs-handle-bg: transparent;
}

```
