### ISSUE TITLE
Can't change background color of the sheet

### ISSUE THREAD

**Issue by DoronTorangy** [stipsan/react-spring-bottom-sheet#132]
I can't change the background color of the sheet.

I tried:
`
[data-rsbs-root] {
    background-color: blue !important;
}
`

`
.background {
  background-color: green !important;
}

<BottomSheet
			className={'background'}
                       style={{background: 'green'}}
>
.....
`

Is there a way to change this?

**Comment by andyrobert3** [comment]
@DoronTorangy how did you do this at the end?

**Comment by karanpratapsingh** [comment]
@andyrobert3 I did it with scss like this and mount the classes based on my theme

Example:

```scss
.light-bottomsheet {
 // update whole overlay
  div[data-rsbs-overlay] {
    background-color: white;
  }
}

.dark-bottomsheet {
 // update whole overlay
  div[data-rsbs-overlay] {
    background-color: black;
   // This is for updating round pill like shape in header (dk what its' called lol
    div[data-rsbs-header]::before {
      background-color:  red;
    }
  }
}
```
