### ISSUE TITLE
How change footer style?

### ISSUE THREAD

**Issue by DodoSpringLove** [stipsan/react-spring-bottom-sheet#221]
![image](https://user-images.githubusercontent.com/26377272/173808989-f8a013e7-ad11-49c4-a5f0-99573d5eadc3.png)

**Comment by AshMW2724** [comment]
Use the css selector `[data-rsbs-footer]` (Add this in another file or the styles.css file you already had to add)

Example:
```css
[data-rsbs-footer] {
  background-color: red;
}
```

**Comment by DodoSpringLove** [comment]
I am sorry to bother you again, but I still want to learn from you how to modify the style of `footer`,like this，i want to user-defined
![image](https://user-images.githubusercontent.com/26377272/176100750-1fd25d19-44cb-4c67-a74a-4fbf6a573f0d.png)

**Comment by kibaek-kimm** [comment]
The PR that allows modifying the style is in draft. https://github.com/stipsan/react-spring-bottom-sheet/pull/56
I don't know why but That's is only way to modify a style of footer(also header).


`[global.css]`
```css
[data-rsbs-footer] {
  box-shadow: none !important;
}
```

`[App.js]`
```javascript
import "./global.css";

// rest of codes

```
